version: "3.9"
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 1
      TZ: Asia/Singapore    
    networks:
      - net01    
  
networks:
  net01:
    external: true
