version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 1
      TZ: Asia/Singapore    
    networks:
      - net01    
  
networks:
  net01:
    external: true
