# syntax=docker/dockerfile:1
# FROM python:3.7-alpine as base
FROM python:3.9-alpine as base
WORKDIR /code
RUN apk add --no-cache --update \
    python3 python3-dev gcc \
    gfortran musl-dev
RUN apk --no-cache add musl-dev linux-headers g++
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_DEBUG=1
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5001
COPY . .
# ########### START NEW IMAGE: DEBUG ################
# FROM base as debug
# RUN pip install debugpy
# CMD python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run -h 0.0.0.0 -p 5000
# ########### START NEW IMAGE: PRODUCTION ###########
# FROM base as prod
CMD ["flask", "run", "-p 5001"]
# CMD flask --app app.py --debug run