version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checker_cron
    restart: always
    volumes:
      - ./run.py:/app/run.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - net01    
  
networks:
  net01:
    external: true
