version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    networks:
      - net01
    depends_on:
      - web

  web:
    build:
      context: ./api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      TZ: Asia/Singapore    
    depends_on:
      - redis  # Ensures the Flask app starts after Redis
    networks:
      - net01

  redis:
    image: "redis:latest"
    restart: always
    networks:
      - net01

networks:
  net01:
    external: true